### ISSUE TITLE
Report doesn't support multiple data in @DataProvider

### ISSUE THREAD

**Issue by asaunin** [sskorol/allure2-testng-report#1]
Please, check, this code for `io.github.sskorol.testcases.common.CommonTests` class:
```
@DataProvider
public static Iterator<Object[]> getData() {
   final List<User> users = Arrays.asList(
           new User("dummyUsername", "dummyPassword"),
           new User("John Doe", "dummyPassword"));
   return users.stream()
                .map(user -> new Object[]{user})
                .iterator();
}

```
**Report displays only the last value from the data provider set**

See the shot:
![image](https://cloud.githubusercontent.com/assets/19559375/26157015/b4b152a8-3b20-11e7-83a8-68b0f612949b.png)

**Comment by sskorol** [comment]
Hi @ASaunin,

Please check `Retries` section at the bottom of the test case. It'll redirect you to the second test case with another data set.

**Comment by asaunin** [comment]
Thx - it's not so clear from a first look

**Comment by sskorol** [comment]
@ASaunin it should be definitely added to docs. Thanks for reporting.
